github: AbuAzad2025

custom:
  - "[https://wa.me/972562150193?text=Hello%20AZAD%20Team,%20I%20want%20to%20support/sponsor%20the%20GitHub%20repository%20via%20IBAN](https://wa.me/972562150193?text=Hello%20AZAD%20Team,%20I%20want%20to%20support/sponsor%20the%20GitHub%20repository%20via%20IBAN)"
  - "mailto:rafideen.ahmadghannam@gmail.com?subject=GitHub%20Repository%20Sponsorship%20%26%20IBAN"
