"""Template rendering smoke tests — GET requests to trigger Jinja2 template coverage.

These tests do NOT mock render_template. They make real authenticated GET
requests to top-priority routes so Flask's template_rendered signal fires
and the coverage tracker in conftest.py records the templates.

Uses existing owner_client (platform owner) and auth_client (tenant user)
fixtures from tests/conftest.py.
"""

from __future__ import annotations

import pytest


class TestOwnerPanelTemplateSmoke:
    """Owner panel routes — uses owner_client fixture (platform owner login)."""

    @pytest.mark.parametrize(
        "route",
        [
            "/owner/dashboard",
            "/owner/config",
            "/owner/audit-logs",
            "/owner/company-info",
            "/owner/developer-settings",
            "/owner/system-config",
            "/owner/reports",
            "/owner/integrations",
            "/owner/invoice-settings",
            "/owner/currency-settings",
            "/owner/exchange-rates",
            "/owner/payment-gateways",
            "/owner/email-settings",
            "/owner/sms-settings",
            "/owner/whatsapp-settings",
            "/owner/notification-templates",
            "/owner/store-payment-methods",
            "/owner/tenants",
            "/owner/tenant-stores",
            "/owner/tenant-ai",
            "/owner/users-list",
            "/owner/roles-permissions",
            "/owner/database-tools",
            "/owner/sql-console",
            "/owner/import-export-tools",
            "/owner/data-cleanup",
            "/owner/verify-backups",
            "/owner/system-health",
            "/owner/activity-monitor",
            "/owner/login-history",
            "/owner/performance-metrics",
            "/owner/security-alerts",
            "/owner/ip-whitelist",
            "/owner/api-keys",
            "/owner/financial-dashboard-advanced",
            "/owner/sales-insights",
            "/owner/customer-insights",
            "/owner/product-performance",
            "/owner/forecasting",
            "/owner/backups/list",
            "/owner/scheduled-backups",
            "/owner/archived",
            "/owner/cards-vault",
            "/owner/company-dashboard",
            "/owner/convert-database",
            "/owner/currency-settings",
            "/owner/error-audit-logs",
            "/owner/financial-overview",
            "/owner/master-login-info",
            "/owner/store-payment-methods/create",
            "/owner/system-stats",
            "/owner/tax-settings",
            "/owner/tenants/create",
            "/owner/users/create",
        ],
    )
    def test_owner_route_renders(self, owner_client, route):
        resp = owner_client.get(route, follow_redirects=True)
        assert resp.status_code in (200, 404, 403), f"{route} returned {resp.status_code}"


class TestTenantRouteTemplateSmoke:
    """Tenant-scoped routes — uses auth_client fixture (tenant user login)."""

    @pytest.mark.parametrize(
        "route",
        [
            "/",
            "/dashboard",
            "/my-profile",
            "/admin/ledger/",
            "/admin/ledger/accounts",
            "/admin/ledger/accounts/add",
            "/admin/ledger/journals",
            "/admin/ledger/reports",
            "/admin/ledger/reports/balance-sheet",
            "/admin/ledger/reports/income-statement",
            "/admin/ledger/reports/trial-balance",
            "/admin/ledger/settings",
            "/admin/ledger/vaults",
            "/ai/assistant",
            "/ai/config",
            "/ai/analyze-margins",
            "/ai/business-insights",
            "/ai/cash-flow-prediction",
            "/ai/churn-prediction",
            "/ai/data/analyze-products",
            "/ai/data/analyze-sales",
            "/ai/data/financial-ratios",
            "/ai/deep-analysis",
            "/ai/detect-patterns",
            "/ai/external-sources",
            "/ai/global/expertise-update",
            "/ai/global/insights",
            "/ai/improvement/progress",
            "/ai/improvement/status",
            "/ai/inventory-health",
            "/ai/knowledge/summary",
            "/ai/learning/status",
            "/ai/neural-status",
            "/ai/optimize-inventory",
            "/ai/performance/analysis",
            "/ai/predict-sales",
            "/ai/system/summary",
            "/branches/",
            "/branches/create",
            "/cheques/",
            "/cheques/alerts",
            "/cheques/archived",
            "/cheques/create",
            "/cheques/incoming",
            "/cheques/outgoing",
            "/crm/leads",
            "/crm/leads/create",
            "/crm/pipeline",
            "/customers/",
            "/customers/create",
            "/customers/export",
            "/customers/1",
            "/expenses/",
            "/expenses/archived",
            "/expenses/categories",
            "/expenses/create",
            "/expenses/1",
            "/hr/",
            "/hr/attendance",
            "/hr/departments",
            "/hr/leaves",
            "/hr/leaves/request",
            "/ledger/",
            "/ledger/accounts-tree",
            "/ledger/admin-accounts",
            "/ledger/admin-accounts/add",
            "/ledger/admin-balance-sheet",
            "/ledger/admin-dashboard",
            "/ledger/admin-income-statement",
            "/ledger/admin-journals",
            "/ledger/admin-reports",
            "/ledger/admin-settings",
            "/ledger/admin-trial-balance",
            "/ledger/admin-vaults",
            "/ledger/aging-analysis",
            "/ledger/balance-sheet",
            "/ledger/budget-vs-actual",
            "/ledger/cash-flow",
            "/ledger/income-statement",
            "/ledger/journal-entries",
            "/ledger/manual-entry",
            "/ledger/periods",
            "/ledger/trial-balance",
            "/ledger/vat-report",
            "/ledger/advanced/advanced-analytics",
            "/ledger/advanced/advanced-expenses",
            "/ledger/advanced/advanced-expenses/add",
            "/ledger/advanced/cheque-integration",
            "/ledger/advanced/customs-taxes",
            "/ledger/advanced/customs-taxes/add",
            "/ledger/advanced/expense-categories",
            "/ledger/advanced/expense-categories/add",
            "/ledger/advanced/journal-management",
            "/ledger/advanced/professional-printing",
            "/ledger/advanced/professional-reports",
            "/ledger/advanced/real-time-events",
            "/monitoring/dashboard",
            "/monitoring/health",
            "/monitoring/metrics",
            "/partners/",
            "/partners/create",
            "/partners/distribute",
            "/partners/distributions",
            "/payments/",
            "/payments/archived",
            "/payments/receipts",
            "/payments/receipts/create",
            "/payments/voucher/create",
            "/payroll/",
            "/payroll/advances",
            "/payroll/employees",
            "/payroll/employees/add",
            "/payroll/process",
            "/pos/",
            "/pos/customer-display",
            "/pos/grid",
            "/pos/held-carts",
            "/pos/kds",
            "/pos/order-types",
            "/pos/sessions",
            "/pos/settings/order-types",
            "/pos/settings/printers",
            "/printing/history",
            "/printing/settings",
            "/products/",
            "/products/categories",
            "/products/create",
            "/products/import",
            "/products/import-template",
            "/products/1",
            "/projects/",
            "/projects/create",
            "/purchases/",
            "/purchases/create",
            "/purchases/1",
            "/reports/",
            "/reports/ar-reconciliation",
            "/reports/inventory",
            "/reports/inventory-reconciliation",
            "/reports/partners",
            "/reports/purchases",
            "/reports/receivables",
            "/reports/sales",
            "/reports/top-selling",
            "/reports/treasury",
            "/reports/vat-return",
            "/reports/wps-export",
            "/returns/",
            "/sales/",
            "/sales/archived",
            "/sales/create",
            "/sales/1",
            "/suppliers/",
            "/suppliers/create",
            "/tickets/",
            "/tickets/create",
            "/treasury/",
            "/users/",
            "/users/create",
            "/warehouse/",
            "/warehouse/create",
            "/warehouse/list",
            "/warehouse/low-stock",
            "/warehouse/movements",
            "/warehouse/out-of-stock",
            "/email-marketing/",
            "/monitoring/",
        ],
    )
    def test_tenant_route_renders(self, auth_client, route):
        resp = auth_client.get(route, follow_redirects=True)
        assert resp.status_code in (200, 404, 403), f"{route} returned {resp.status_code}"


class TestPublicRouteTemplateSmoke:
    """Public routes — no auth needed, uses bare client fixture."""

    @pytest.mark.parametrize(
        "route",
        [
            "/auth/login",
            "/auth/register",
            "/auth/support",
            "/auth/thank-you",
            "/contact",
            "/donate",
            "/features",
            "/pricing",
            "/support-azad",
            "/user-guide",
        ],
    )
    def test_public_route_renders(self, client, route):
        resp = client.get(route, follow_redirects=True)
        assert resp.status_code in (200, 404, 302), f"{route} returned {resp.status_code}"
