"""add tenant_store display_currency

Revision ID: 004deb545b88
Revises: a63547a6f0d7
Create Date: 2026-07-31 15:23:59.977353

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "004deb545b88"
down_revision = "a63547a6f0d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenant_stores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("display_currency", sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenant_stores", schema=None) as batch_op:
        batch_op.drop_column("display_currency")

    # ### end Alembic commands ###
