"""add sync_batch and api_key tenant_id for pos sync

Revision ID: 21b19821edf8
Revises: e75de4aeafea
Create Date: 2026-07-22 23:57:27.071981

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21b19821edf8"
down_revision = "e75de4aeafea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_api_keys_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_foreign_key(None, "tenants", ["tenant_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_api_keys_tenant_id"))
        batch_op.drop_column("tenant_id")

    # ### end Alembic commands ###
