"""add_branch_to_accounting_models

Revision ID: 24ceeacb537a
Revises: a069786bc9a5
Create Date: 2026-03-01 04:42:40.865869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ceeacb537a'
down_revision = 'a069786bc9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advanced_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_advanced_expenses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_budgets_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fixed_assets_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fixed_assets_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_budgets_branch_id'))
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('advanced_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_advanced_expenses_branch_id'))
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
