"""add_branch_to_simple_expense

Revision ID: 31def1234567
Revises: 24ceeacb537a
Create Date: 2026-03-01 05:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31def1234567'
down_revision = '24ceeacb537a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_reversed', sa.Boolean(), nullable=True, server_default='0'))
        
        batch_op.create_index(batch_op.f('ix_expenses_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_is_reversed'), ['is_reversed'], unique=False)
        
        batch_op.create_foreign_key('fk_expenses_branch_id', 'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_branch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_is_reversed'))
        batch_op.drop_index(batch_op.f('ix_expenses_branch_id'))
        batch_op.drop_column('is_reversed')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
