"""autogenerate schema drift fixes

Revision ID: 40a8882b3f69
Revises: ecad0902bdb5
Create Date: 2026-06-09 13:03:23.311857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a8882b3f69'
down_revision = 'ecad0902bdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_archived_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_archived_records_tenant_table', ['tenant_id', 'table_name'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('bank_reconciliation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_bank_reconciliation_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('bank_reconciliations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_bank_reconciliations_reconciliation_number'))
        batch_op.create_index(batch_op.f('ix_bank_reconciliations_reconciliation_number'), ['reconciliation_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_reconciliations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_bank_reconciliations_tenant_number', ['tenant_id', 'reconciliation_number'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_budget_lines_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_budgets_budget_number'))
        batch_op.create_index(batch_op.f('ix_budgets_budget_number'), ['budget_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_budgets_tenant_budget_number', ['tenant_id', 'budget_number'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('card_vault', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('product_serials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_product_serials_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_serials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_product_serials_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('card_vault', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_budgets_tenant_budget_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_budgets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_budget_number'))
        batch_op.create_index(batch_op.f('ix_budgets_budget_number'), ['budget_number'], unique=True)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_budget_lines_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('bank_reconciliations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_bank_reconciliations_tenant_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_bank_reconciliations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bank_reconciliations_reconciliation_number'))
        batch_op.create_index(batch_op.f('ix_bank_reconciliations_reconciliation_number'), ['reconciliation_number'], unique=True)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('bank_reconciliation_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bank_reconciliation_items_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('archived_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_archived_records_tenant_table')
        batch_op.drop_index(batch_op.f('ix_archived_records_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
