"""Sync model changes: pos_session, platform fee fields

Revision ID: a41dbc9113d5
Revises: 8a4bf80ac1b0
Create Date: 2026-06-11 17:45:24.032313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41dbc9113d5'
down_revision = '8a4bf80ac1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_reconcile', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_gl_accounts_sub_type'), ['sub_type'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azad_platform_fee_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('subscription_monthly_fee_aed', sa.Numeric(precision=15, scale=3), nullable=True))
        batch_op.add_column(sa.Column('subscription_yearly_fee_aed', sa.Numeric(precision=15, scale=3), nullable=True))
        batch_op.add_column(sa.Column('subscription_perpetual_fee_aed', sa.Numeric(precision=15, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('subscription_perpetual_fee_aed')
        batch_op.drop_column('subscription_yearly_fee_aed')
        batch_op.drop_column('subscription_monthly_fee_aed')
        batch_op.drop_column('azad_platform_fee_rate')

    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_accounts_sub_type'))
        batch_op.drop_column('is_reconcile')
        batch_op.drop_column('sub_type')

    # ### end Alembic commands ###
