"""add azad_platform_fee_include_offline toggle

Revision ID: a63547a6f0d7
Revises: 313a6a9fb20f
Create Date: 2026-07-31 14:25:47.845815

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a63547a6f0d7"
down_revision = "313a6a9fb20f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("azad_platform_fee_include_offline", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_settings", schema=None) as batch_op:
        batch_op.drop_column("azad_platform_fee_include_offline")

    # ### end Alembic commands ###
