"""audit_001_add_missing_indexes_and_fk_cascade

Revision ID: audit_001
Revises: 6f0a6712e08b
Create Date: 2026-06-10 05:38:22

Indexes: 164
FKs with ON DELETE CASCADE: 57
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = 'audit_001'
down_revision = '6f0a6712e08b'
branch_labels = None
depends_on = None


def upgrade():
    # ── Missing indexes ──
    op.create_index(op.f('ix_advanced_expenses_created_at'), 'advanced_expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_advanced_expenses_approved_by'), 'advanced_expenses', ['approved_by'], unique=False)
    op.create_index(op.f('ix_advanced_expenses_category_id'), 'advanced_expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_advanced_expenses_created_by'), 'advanced_expenses', ['created_by'], unique=False)
    op.create_index(op.f('ix_advanced_expenses_gl_journal_entry_id'), 'advanced_expenses', ['gl_journal_entry_id'], unique=False)
    op.create_index(op.f('ix_advanced_expenses_reversed_by'), 'advanced_expenses', ['reversed_by'], unique=False)
    op.create_index(op.f('ix_advanced_expenses_supplier_id'), 'advanced_expenses', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_ai_expertise_created_at'), 'ai_expertise', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_interactions_created_at'), 'ai_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_memories_created_at'), 'ai_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_created_by'), 'api_keys', ['created_by'], unique=False)
    op.create_index(op.f('ix_archived_records_archived_by'), 'archived_records', ['archived_by'], unique=False)
    op.create_index(op.f('ix_azad_platform_fees_created_at'), 'azad_platform_fees', ['created_at'], unique=False)
    op.create_index(op.f('ix_bank_reconciliation_items_cheque_id'), 'bank_reconciliation_items', ['cheque_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliation_items_journal_entry_id'), 'bank_reconciliation_items', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliation_items_reconciliation_id'), 'bank_reconciliation_items', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_created_at'), 'bank_reconciliations', ['created_at'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_approved_by'), 'bank_reconciliations', ['approved_by'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_bank_account_id'), 'bank_reconciliations', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_created_by'), 'bank_reconciliations', ['created_by'], unique=False)
    op.create_index(op.f('ix_branches_created_at'), 'branches', ['created_at'], unique=False)
    op.create_index(op.f('ix_branches_is_active'), 'branches', ['is_active'], unique=False)
    op.create_index(op.f('ix_budget_lines_account_id'), 'budget_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_budget_id'), 'budget_lines', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budgets_created_at'), 'budgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_budgets_approved_by'), 'budgets', ['approved_by'], unique=False)
    op.create_index(op.f('ix_budgets_created_by'), 'budgets', ['created_by'], unique=False)
    op.create_index(op.f('ix_card_payments_status'), 'card_payments', ['status'], unique=False)
    op.create_index(op.f('ix_card_vault_is_active'), 'card_vault', ['is_active'], unique=False)
    op.create_index(op.f('ix_card_vault_created_by'), 'card_vault', ['created_by'], unique=False)
    op.create_index(op.f('ix_cash_boxes_created_at'), 'cash_boxes', ['created_at'], unique=False)
    op.create_index(op.f('ix_cheques_created_at'), 'cheques', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_centers_created_at'), 'cost_centers', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_centers_manager_id'), 'cost_centers', ['manager_id'], unique=False)
    op.create_index(op.f('ix_cost_centers_parent_id'), 'cost_centers', ['parent_id'], unique=False)
    op.create_index(op.f('ix_currencies_created_at'), 'currencies', ['created_at'], unique=False)
    op.create_index(op.f('ix_currencies_is_active'), 'currencies', ['is_active'], unique=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customs_taxes_created_at'), 'customs_taxes', ['created_at'], unique=False)
    op.create_index(op.f('ix_customs_taxes_is_active'), 'customs_taxes', ['is_active'], unique=False)
    op.create_index(op.f('ix_customs_taxes_gl_account_id'), 'customs_taxes', ['gl_account_id'], unique=False)
    op.create_index(op.f('ix_depreciation_schedules_created_at'), 'depreciation_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_depreciation_schedules_journal_entry_id'), 'depreciation_schedules', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_index(op.f('ix_employees_created_at'), 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_error_audit_logs_resolved_by'), 'error_audit_logs', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_exchange_rate_records_created_at'), 'exchange_rate_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_exchange_rate_records_created_by'), 'exchange_rate_records', ['created_by'], unique=False)
    op.create_index(op.f('ix_exchange_rates_created_at'), 'exchange_rates', ['created_at'], unique=False)
    op.create_index(op.f('ix_exchange_rates_created_by'), 'exchange_rates', ['created_by'], unique=False)
    op.create_index(op.f('ix_expense_categories_created_at'), 'expense_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_expense_categories_is_active'), 'expense_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_fixed_assets_created_at'), 'fixed_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_fixed_assets_asset_account_id'), 'fixed_assets', ['asset_account_id'], unique=False)
    op.create_index(op.f('ix_fixed_assets_cost_center_id'), 'fixed_assets', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_fixed_assets_created_by'), 'fixed_assets', ['created_by'], unique=False)
    op.create_index(op.f('ix_fixed_assets_depreciation_account_id'), 'fixed_assets', ['depreciation_account_id'], unique=False)
    op.create_index(op.f('ix_fixed_assets_expense_account_id'), 'fixed_assets', ['expense_account_id'], unique=False)
    op.create_index(op.f('ix_gl_account_mappings_created_at'), 'gl_account_mappings', ['created_at'], unique=False)
    op.create_index(op.f('ix_gl_accounts_created_at'), 'gl_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_gl_accounts_is_active'), 'gl_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_gl_accounts_parent_id'), 'gl_accounts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_gl_journal_entries_created_at'), 'gl_journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_gl_journal_entries_created_by'), 'gl_journal_entries', ['created_by'], unique=False)
    op.create_index(op.f('ix_gl_journal_entries_reversed_entry_id'), 'gl_journal_entries', ['reversed_entry_id'], unique=False)
    op.create_index(op.f('ix_gl_periods_created_at'), 'gl_periods', ['created_at'], unique=False)
    op.create_index(op.f('ix_gl_periods_closed_by'), 'gl_periods', ['closed_by'], unique=False)
    op.create_index(op.f('ix_integration_settings_created_at'), 'integration_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_integration_settings_updated_by'), 'integration_settings', ['updated_by'], unique=False)
    op.create_index(op.f('ix_invoice_settings_created_at'), 'invoice_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoice_settings_is_active'), 'invoice_settings', ['is_active'], unique=False)
    op.create_index(op.f('ix_invoice_settings_updated_by'), 'invoice_settings', ['updated_by'], unique=False)
    op.create_index(op.f('ix_journal_entry_audits_journal_entry_id'), 'journal_entry_audits', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_audits_performed_by'), 'journal_entry_audits', ['performed_by'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_package_purchases_created_at'), 'package_purchases', ['created_at'], unique=False)
    op.create_index(op.f('ix_package_purchases_package_id'), 'package_purchases', ['package_id'], unique=False)
    op.create_index(op.f('ix_packages_created_at'), 'packages', ['created_at'], unique=False)
    op.create_index(op.f('ix_packages_is_active'), 'packages', ['is_active'], unique=False)
    op.create_index(op.f('ix_partner_commission_entries_created_at'), 'partner_commission_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_commission_entries_product_id'), 'partner_commission_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_partner_commission_entries_sale_line_id'), 'partner_commission_entries', ['sale_line_id'], unique=False)
    op.create_index(op.f('ix_partner_profit_distributions_created_at'), 'partner_profit_distributions', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_profit_distributions_status'), 'partner_profit_distributions', ['status'], unique=False)
    op.create_index(op.f('ix_partner_profit_distributions_approved_by'), 'partner_profit_distributions', ['approved_by'], unique=False)
    op.create_index(op.f('ix_partner_profit_distributions_created_by'), 'partner_profit_distributions', ['created_by'], unique=False)
    op.create_index(op.f('ix_partner_transactions_created_at'), 'partner_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_transactions_created_by'), 'partner_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_partners_created_at'), 'partners', ['created_at'], unique=False)
    op.create_index(op.f('ix_partners_is_active'), 'partners', ['is_active'], unique=False)
    op.create_index(op.f('ix_payment_logs_created_at'), 'payment_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_logs_vault_id'), 'payment_logs', ['vault_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_vault_id'), 'payment_transactions', ['vault_id'], unique=False)
    op.create_index(op.f('ix_payment_vault_created_at'), 'payment_vault', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payroll_transactions_status'), 'payroll_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payroll_transactions_branch_id'), 'payroll_transactions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_payroll_transactions_created_by'), 'payroll_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_payroll_transactions_employee_id'), 'payroll_transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_transactions_gl_entry_id'), 'payroll_transactions', ['gl_entry_id'], unique=False)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_categories_created_at'), 'product_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_categories_is_active'), 'product_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_product_cost_history_created_at'), 'product_cost_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_partners_created_at'), 'product_partners', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_return_lines_product_id'), 'product_return_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_return_lines_sale_line_id'), 'product_return_lines', ['sale_line_id'], unique=False)
    op.create_index(op.f('ix_product_returns_created_at'), 'product_returns', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_serials_created_at'), 'product_serials', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_serials_purchase_line_id'), 'product_serials', ['purchase_line_id'], unique=False)
    op.create_index(op.f('ix_product_serials_sale_line_id'), 'product_serials', ['sale_line_id'], unique=False)
    op.create_index(op.f('ix_product_warehouse_costs_created_at'), 'product_warehouse_costs', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_warehouse_costs_updated_by_movement_id'), 'product_warehouse_costs', ['updated_by_movement_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_profit_centers_created_at'), 'profit_centers', ['created_at'], unique=False)
    op.create_index(op.f('ix_profit_centers_manager_id'), 'profit_centers', ['manager_id'], unique=False)
    op.create_index(op.f('ix_profit_centers_parent_id'), 'profit_centers', ['parent_id'], unique=False)
    op.create_index(op.f('ix_purchase_lines_product_id'), 'purchase_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchases_created_at'), 'purchases', ['created_at'], unique=False)
    op.create_index(op.f('ix_receipts_created_at'), 'receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_salary_advances_created_at'), 'salary_advances', ['created_at'], unique=False)
    op.create_index(op.f('ix_salary_advances_status'), 'salary_advances', ['status'], unique=False)
    op.create_index(op.f('ix_salary_advances_created_by'), 'salary_advances', ['created_by'], unique=False)
    op.create_index(op.f('ix_salary_advances_employee_id'), 'salary_advances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_advances_gl_entry_id'), 'salary_advances', ['gl_entry_id'], unique=False)
    op.create_index(op.f('ix_sale_lines_product_id'), 'sale_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_created_at'), 'security_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_resolved_by'), 'security_alerts', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_security_alerts_user_id'), 'security_alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_shop_customer_accounts_created_at'), 'shop_customer_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_customer_accounts_is_active'), 'shop_customer_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_store_coupons_created_at'), 'store_coupons', ['created_at'], unique=False)
    op.create_index(op.f('ix_store_coupons_is_active'), 'store_coupons', ['is_active'], unique=False)
    op.create_index(op.f('ix_store_payment_methods_created_at'), 'store_payment_methods', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_created_by'), 'suppliers', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_settings_is_active'), 'system_settings', ['is_active'], unique=False)
    op.create_index(op.f('ix_system_settings_updated_by'), 'system_settings', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tax_calculation_rules_created_at'), 'tax_calculation_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_tax_calculation_rules_is_active'), 'tax_calculation_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_tax_calculation_rules_tax_id'), 'tax_calculation_rules', ['tax_id'], unique=False)
    op.create_index(op.f('ix_tenant_stores_created_at'), 'tenant_stores', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_is_suspended'), 'tenants', ['is_suspended'], unique=False)
    op.create_index(op.f('ix_tenants_created_by'), 'tenants', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_warehouses_created_at'), 'warehouses', ['created_at'], unique=False)
    op.create_index(op.f('ix_warehouses_is_active'), 'warehouses', ['is_active'], unique=False)
    op.create_index(op.f('ix_warehouses_manager_id'), 'warehouses', ['manager_id'], unique=False)
    op.create_index(op.f('ix_warehouses_parent_id'), 'warehouses', ['parent_id'], unique=False)

    # ── ON DELETE CASCADE on tenant_id FKs ──
    op.drop_constraint('fk_advanced_expenses_tenant_id', 'advanced_expenses', type_='foreignkey')
    op.create_foreign_key('fk_advanced_expenses_tenant_id', 'advanced_expenses', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('archived_records_tenant_id_fkey', 'archived_records', type_='foreignkey')
    op.create_foreign_key('archived_records_tenant_id_fkey', 'archived_records', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('audit_logs_tenant_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_tenant_id_fkey', 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('azad_platform_fees_tenant_id_fkey', 'azad_platform_fees', type_='foreignkey')
    op.create_foreign_key('azad_platform_fees_tenant_id_fkey', 'azad_platform_fees', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('bank_reconciliation_items_tenant_id_fkey', 'bank_reconciliation_items', type_='foreignkey')
    op.create_foreign_key('bank_reconciliation_items_tenant_id_fkey', 'bank_reconciliation_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('bank_reconciliations_tenant_id_fkey', 'bank_reconciliations', type_='foreignkey')
    op.create_foreign_key('bank_reconciliations_tenant_id_fkey', 'bank_reconciliations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('branches_tenant_id_fkey', 'branches', type_='foreignkey')
    op.create_foreign_key('branches_tenant_id_fkey', 'branches', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('budget_lines_tenant_id_fkey', 'budget_lines', type_='foreignkey')
    op.create_foreign_key('budget_lines_tenant_id_fkey', 'budget_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('budgets_tenant_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key('budgets_tenant_id_fkey', 'budgets', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('card_vault_tenant_id_fkey', 'card_vault', type_='foreignkey')
    op.create_foreign_key('card_vault_tenant_id_fkey', 'card_vault', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cash_boxes_tenant_id_fkey', 'cash_boxes', type_='foreignkey')
    op.create_foreign_key('cash_boxes_tenant_id_fkey', 'cash_boxes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_cheques_tenant_id', 'cheques', type_='foreignkey')
    op.create_foreign_key('fk_cheques_tenant_id', 'cheques', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cost_centers_tenant_id_fkey', 'cost_centers', type_='foreignkey')
    op.create_foreign_key('cost_centers_tenant_id_fkey', 'cost_centers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_customers_tenant_id', 'customers', type_='foreignkey')
    op.create_foreign_key('fk_customers_tenant_id', 'customers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_customs_taxes_tenant_id', 'customs_taxes', type_='foreignkey')
    op.create_foreign_key('fk_customs_taxes_tenant_id', 'customs_taxes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_donations_tenant_id', 'donations', type_='foreignkey')
    op.create_foreign_key('fk_donations_tenant_id', 'donations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_employees_tenant_id', 'employees', type_='foreignkey')
    op.create_foreign_key('fk_employees_tenant_id', 'employees', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('error_audit_logs_tenant_id_fkey', 'error_audit_logs', type_='foreignkey')
    op.create_foreign_key('error_audit_logs_tenant_id_fkey', 'error_audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exchange_rate_records_tenant_id_fkey', 'exchange_rate_records', type_='foreignkey')
    op.create_foreign_key('exchange_rate_records_tenant_id_fkey', 'exchange_rate_records', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_expense_categories_tenant_id', 'expense_categories', type_='foreignkey')
    op.create_foreign_key('fk_expense_categories_tenant_id', 'expense_categories', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_expenses_tenant_id', 'expenses', type_='foreignkey')
    op.create_foreign_key('fk_expenses_tenant_id', 'expenses', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_fixed_assets_tenant_id', 'fixed_assets', type_='foreignkey')
    op.create_foreign_key('fk_fixed_assets_tenant_id', 'fixed_assets', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_gl_accounts_tenant_id', 'gl_accounts', type_='foreignkey')
    op.create_foreign_key('fk_gl_accounts_tenant_id', 'gl_accounts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_gl_journal_entries_tenant_id', 'gl_journal_entries', type_='foreignkey')
    op.create_foreign_key('fk_gl_journal_entries_tenant_id', 'gl_journal_entries', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_gl_journal_lines_tenant_id', 'gl_journal_lines', type_='foreignkey')
    op.create_foreign_key('fk_gl_journal_lines_tenant_id', 'gl_journal_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('gl_periods_tenant_id_fkey', 'gl_periods', type_='foreignkey')
    op.create_foreign_key('gl_periods_tenant_id_fkey', 'gl_periods', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_invoice_settings_tenant_id', 'invoice_settings', type_='foreignkey')
    op.create_foreign_key('fk_invoice_settings_tenant_id', 'invoice_settings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('partner_commission_entries_tenant_id_fkey', 'partner_commission_entries', type_='foreignkey')
    op.create_foreign_key('partner_commission_entries_tenant_id_fkey', 'partner_commission_entries', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('partner_profit_distributions_tenant_id_fkey', 'partner_profit_distributions', type_='foreignkey')
    op.create_foreign_key('partner_profit_distributions_tenant_id_fkey', 'partner_profit_distributions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('partner_transactions_tenant_id_fkey', 'partner_transactions', type_='foreignkey')
    op.create_foreign_key('partner_transactions_tenant_id_fkey', 'partner_transactions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('partners_tenant_id_fkey', 'partners', type_='foreignkey')
    op.create_foreign_key('partners_tenant_id_fkey', 'partners', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_payment_vault_tenant_id', 'payment_vault', type_='foreignkey')
    op.create_foreign_key('fk_payment_vault_tenant_id', 'payment_vault', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_payments_tenant_id', 'payments', type_='foreignkey')
    op.create_foreign_key('fk_payments_tenant_id', 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_payroll_transactions_tenant_id', 'payroll_transactions', type_='foreignkey')
    op.create_foreign_key('fk_payroll_transactions_tenant_id', 'payroll_transactions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_product_categories_tenant_id', 'product_categories', type_='foreignkey')
    op.create_foreign_key('fk_product_categories_tenant_id', 'product_categories', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_cost_history_tenant_id_fkey', 'product_cost_history', type_='foreignkey')
    op.create_foreign_key('product_cost_history_tenant_id_fkey', 'product_cost_history', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_product_partners_tenant_id', 'product_partners', type_='foreignkey')
    op.create_foreign_key('fk_product_partners_tenant_id', 'product_partners', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_product_return_lines_tenant_id', 'product_return_lines', type_='foreignkey')
    op.create_foreign_key('fk_product_return_lines_tenant_id', 'product_return_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_product_returns_tenant_id', 'product_returns', type_='foreignkey')
    op.create_foreign_key('fk_product_returns_tenant_id', 'product_returns', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_serials_tenant_id_fkey', 'product_serials', type_='foreignkey')
    op.create_foreign_key('product_serials_tenant_id_fkey', 'product_serials', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_warehouse_costs_tenant_id_fkey', 'product_warehouse_costs', type_='foreignkey')
    op.create_foreign_key('product_warehouse_costs_tenant_id_fkey', 'product_warehouse_costs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_products_tenant_id', 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_tenant_id', 'products', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profit_centers_tenant_id_fkey', 'profit_centers', type_='foreignkey')
    op.create_foreign_key('profit_centers_tenant_id_fkey', 'profit_centers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_purchase_lines_tenant_id', 'purchase_lines', type_='foreignkey')
    op.create_foreign_key('fk_purchase_lines_tenant_id', 'purchase_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_purchases_tenant_id', 'purchases', type_='foreignkey')
    op.create_foreign_key('fk_purchases_tenant_id', 'purchases', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_receipts_tenant_id', 'receipts', type_='foreignkey')
    op.create_foreign_key('fk_receipts_tenant_id', 'receipts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_salary_advances_tenant_id', 'salary_advances', type_='foreignkey')
    op.create_foreign_key('fk_salary_advances_tenant_id', 'salary_advances', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_sale_lines_tenant_id', 'sale_lines', type_='foreignkey')
    op.create_foreign_key('fk_sale_lines_tenant_id', 'sale_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_sales_tenant_id', 'sales', type_='foreignkey')
    op.create_foreign_key('fk_sales_tenant_id', 'sales', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shop_customer_accounts_tenant_id_fkey', 'shop_customer_accounts', type_='foreignkey')
    op.create_foreign_key('shop_customer_accounts_tenant_id_fkey', 'shop_customer_accounts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_stock_movements_tenant_id', 'stock_movements', type_='foreignkey')
    op.create_foreign_key('fk_stock_movements_tenant_id', 'stock_movements', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('store_coupons_tenant_id_fkey', 'store_coupons', type_='foreignkey')
    op.create_foreign_key('store_coupons_tenant_id_fkey', 'store_coupons', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_suppliers_tenant_id', 'suppliers', type_='foreignkey')
    op.create_foreign_key('fk_suppliers_tenant_id', 'suppliers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_tax_calculation_rules_tenant_id', 'tax_calculation_rules', type_='foreignkey')
    op.create_foreign_key('fk_tax_calculation_rules_tenant_id', 'tax_calculation_rules', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tenant_stores_tenant_id_fkey', 'tenant_stores', type_='foreignkey')
    op.create_foreign_key('tenant_stores_tenant_id_fkey', 'tenant_stores', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_users_tenant_id', 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_tenant_id', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_warehouses_tenant_id', 'warehouses', type_='foreignkey')
    op.create_foreign_key('fk_warehouses_tenant_id', 'warehouses', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ── Restore original FK constraints ──
    op.drop_constraint('fk_warehouses_tenant_id', 'warehouses', type_='foreignkey')
    op.create_foreign_key('fk_warehouses_tenant_id', 'warehouses', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_users_tenant_id', 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_tenant_id', 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('tenant_stores_tenant_id_fkey', 'tenant_stores', type_='foreignkey')
    op.create_foreign_key('tenant_stores_tenant_id_fkey', 'tenant_stores', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_tax_calculation_rules_tenant_id', 'tax_calculation_rules', type_='foreignkey')
    op.create_foreign_key('fk_tax_calculation_rules_tenant_id', 'tax_calculation_rules', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_suppliers_tenant_id', 'suppliers', type_='foreignkey')
    op.create_foreign_key('fk_suppliers_tenant_id', 'suppliers', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('store_coupons_tenant_id_fkey', 'store_coupons', type_='foreignkey')
    op.create_foreign_key('store_coupons_tenant_id_fkey', 'store_coupons', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_stock_movements_tenant_id', 'stock_movements', type_='foreignkey')
    op.create_foreign_key('fk_stock_movements_tenant_id', 'stock_movements', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('shop_customer_accounts_tenant_id_fkey', 'shop_customer_accounts', type_='foreignkey')
    op.create_foreign_key('shop_customer_accounts_tenant_id_fkey', 'shop_customer_accounts', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_sales_tenant_id', 'sales', type_='foreignkey')
    op.create_foreign_key('fk_sales_tenant_id', 'sales', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_sale_lines_tenant_id', 'sale_lines', type_='foreignkey')
    op.create_foreign_key('fk_sale_lines_tenant_id', 'sale_lines', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_salary_advances_tenant_id', 'salary_advances', type_='foreignkey')
    op.create_foreign_key('fk_salary_advances_tenant_id', 'salary_advances', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_receipts_tenant_id', 'receipts', type_='foreignkey')
    op.create_foreign_key('fk_receipts_tenant_id', 'receipts', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_purchases_tenant_id', 'purchases', type_='foreignkey')
    op.create_foreign_key('fk_purchases_tenant_id', 'purchases', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_purchase_lines_tenant_id', 'purchase_lines', type_='foreignkey')
    op.create_foreign_key('fk_purchase_lines_tenant_id', 'purchase_lines', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('profit_centers_tenant_id_fkey', 'profit_centers', type_='foreignkey')
    op.create_foreign_key('profit_centers_tenant_id_fkey', 'profit_centers', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_products_tenant_id', 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_tenant_id', 'products', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('product_warehouse_costs_tenant_id_fkey', 'product_warehouse_costs', type_='foreignkey')
    op.create_foreign_key('product_warehouse_costs_tenant_id_fkey', 'product_warehouse_costs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('product_serials_tenant_id_fkey', 'product_serials', type_='foreignkey')
    op.create_foreign_key('product_serials_tenant_id_fkey', 'product_serials', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_product_returns_tenant_id', 'product_returns', type_='foreignkey')
    op.create_foreign_key('fk_product_returns_tenant_id', 'product_returns', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_product_return_lines_tenant_id', 'product_return_lines', type_='foreignkey')
    op.create_foreign_key('fk_product_return_lines_tenant_id', 'product_return_lines', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_product_partners_tenant_id', 'product_partners', type_='foreignkey')
    op.create_foreign_key('fk_product_partners_tenant_id', 'product_partners', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('product_cost_history_tenant_id_fkey', 'product_cost_history', type_='foreignkey')
    op.create_foreign_key('product_cost_history_tenant_id_fkey', 'product_cost_history', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_product_categories_tenant_id', 'product_categories', type_='foreignkey')
    op.create_foreign_key('fk_product_categories_tenant_id', 'product_categories', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_payroll_transactions_tenant_id', 'payroll_transactions', type_='foreignkey')
    op.create_foreign_key('fk_payroll_transactions_tenant_id', 'payroll_transactions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_payments_tenant_id', 'payments', type_='foreignkey')
    op.create_foreign_key('fk_payments_tenant_id', 'payments', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_payment_vault_tenant_id', 'payment_vault', type_='foreignkey')
    op.create_foreign_key('fk_payment_vault_tenant_id', 'payment_vault', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('partners_tenant_id_fkey', 'partners', type_='foreignkey')
    op.create_foreign_key('partners_tenant_id_fkey', 'partners', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('partner_transactions_tenant_id_fkey', 'partner_transactions', type_='foreignkey')
    op.create_foreign_key('partner_transactions_tenant_id_fkey', 'partner_transactions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('partner_profit_distributions_tenant_id_fkey', 'partner_profit_distributions', type_='foreignkey')
    op.create_foreign_key('partner_profit_distributions_tenant_id_fkey', 'partner_profit_distributions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('partner_commission_entries_tenant_id_fkey', 'partner_commission_entries', type_='foreignkey')
    op.create_foreign_key('partner_commission_entries_tenant_id_fkey', 'partner_commission_entries', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_invoice_settings_tenant_id', 'invoice_settings', type_='foreignkey')
    op.create_foreign_key('fk_invoice_settings_tenant_id', 'invoice_settings', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('gl_periods_tenant_id_fkey', 'gl_periods', type_='foreignkey')
    op.create_foreign_key('gl_periods_tenant_id_fkey', 'gl_periods', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_gl_journal_lines_tenant_id', 'gl_journal_lines', type_='foreignkey')
    op.create_foreign_key('fk_gl_journal_lines_tenant_id', 'gl_journal_lines', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_gl_journal_entries_tenant_id', 'gl_journal_entries', type_='foreignkey')
    op.create_foreign_key('fk_gl_journal_entries_tenant_id', 'gl_journal_entries', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_gl_accounts_tenant_id', 'gl_accounts', type_='foreignkey')
    op.create_foreign_key('fk_gl_accounts_tenant_id', 'gl_accounts', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_fixed_assets_tenant_id', 'fixed_assets', type_='foreignkey')
    op.create_foreign_key('fk_fixed_assets_tenant_id', 'fixed_assets', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_expenses_tenant_id', 'expenses', type_='foreignkey')
    op.create_foreign_key('fk_expenses_tenant_id', 'expenses', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_expense_categories_tenant_id', 'expense_categories', type_='foreignkey')
    op.create_foreign_key('fk_expense_categories_tenant_id', 'expense_categories', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('exchange_rate_records_tenant_id_fkey', 'exchange_rate_records', type_='foreignkey')
    op.create_foreign_key('exchange_rate_records_tenant_id_fkey', 'exchange_rate_records', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('error_audit_logs_tenant_id_fkey', 'error_audit_logs', type_='foreignkey')
    op.create_foreign_key('error_audit_logs_tenant_id_fkey', 'error_audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_employees_tenant_id', 'employees', type_='foreignkey')
    op.create_foreign_key('fk_employees_tenant_id', 'employees', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_donations_tenant_id', 'donations', type_='foreignkey')
    op.create_foreign_key('fk_donations_tenant_id', 'donations', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_customs_taxes_tenant_id', 'customs_taxes', type_='foreignkey')
    op.create_foreign_key('fk_customs_taxes_tenant_id', 'customs_taxes', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_customers_tenant_id', 'customers', type_='foreignkey')
    op.create_foreign_key('fk_customers_tenant_id', 'customers', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('cost_centers_tenant_id_fkey', 'cost_centers', type_='foreignkey')
    op.create_foreign_key('cost_centers_tenant_id_fkey', 'cost_centers', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_cheques_tenant_id', 'cheques', type_='foreignkey')
    op.create_foreign_key('fk_cheques_tenant_id', 'cheques', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('cash_boxes_tenant_id_fkey', 'cash_boxes', type_='foreignkey')
    op.create_foreign_key('cash_boxes_tenant_id_fkey', 'cash_boxes', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('card_vault_tenant_id_fkey', 'card_vault', type_='foreignkey')
    op.create_foreign_key('card_vault_tenant_id_fkey', 'card_vault', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('budgets_tenant_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key('budgets_tenant_id_fkey', 'budgets', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('budget_lines_tenant_id_fkey', 'budget_lines', type_='foreignkey')
    op.create_foreign_key('budget_lines_tenant_id_fkey', 'budget_lines', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('branches_tenant_id_fkey', 'branches', type_='foreignkey')
    op.create_foreign_key('branches_tenant_id_fkey', 'branches', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('bank_reconciliations_tenant_id_fkey', 'bank_reconciliations', type_='foreignkey')
    op.create_foreign_key('bank_reconciliations_tenant_id_fkey', 'bank_reconciliations', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('bank_reconciliation_items_tenant_id_fkey', 'bank_reconciliation_items', type_='foreignkey')
    op.create_foreign_key('bank_reconciliation_items_tenant_id_fkey', 'bank_reconciliation_items', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('azad_platform_fees_tenant_id_fkey', 'azad_platform_fees', type_='foreignkey')
    op.create_foreign_key('azad_platform_fees_tenant_id_fkey', 'azad_platform_fees', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('audit_logs_tenant_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_tenant_id_fkey', 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('archived_records_tenant_id_fkey', 'archived_records', type_='foreignkey')
    op.create_foreign_key('archived_records_tenant_id_fkey', 'archived_records', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('fk_advanced_expenses_tenant_id', 'advanced_expenses', type_='foreignkey')
    op.create_foreign_key('fk_advanced_expenses_tenant_id', 'advanced_expenses', 'tenants', ['tenant_id'], ['id'])

    # ── Drop added indexes ──
    op.drop_index(op.f('ix_warehouses_parent_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_manager_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_is_active'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_created_at'), table_name='warehouses')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_tenants_created_by'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_suspended'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_index(op.f('ix_tenant_stores_created_at'), table_name='tenant_stores')
    op.drop_index(op.f('ix_tax_calculation_rules_tax_id'), table_name='tax_calculation_rules')
    op.drop_index(op.f('ix_tax_calculation_rules_is_active'), table_name='tax_calculation_rules')
    op.drop_index(op.f('ix_tax_calculation_rules_created_at'), table_name='tax_calculation_rules')
    op.drop_index(op.f('ix_system_settings_updated_by'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_is_active'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_index(op.f('ix_suppliers_created_by'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_index(op.f('ix_store_payment_methods_created_at'), table_name='store_payment_methods')
    op.drop_index(op.f('ix_store_coupons_is_active'), table_name='store_coupons')
    op.drop_index(op.f('ix_store_coupons_created_at'), table_name='store_coupons')
    op.drop_index(op.f('ix_stock_movements_warehouse_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_shop_customer_accounts_is_active'), table_name='shop_customer_accounts')
    op.drop_index(op.f('ix_shop_customer_accounts_created_at'), table_name='shop_customer_accounts')
    op.drop_index(op.f('ix_security_alerts_user_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_resolved_by'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_created_at'), table_name='security_alerts')
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.drop_index(op.f('ix_sale_lines_product_id'), table_name='sale_lines')
    op.drop_index(op.f('ix_salary_advances_gl_entry_id'), table_name='salary_advances')
    op.drop_index(op.f('ix_salary_advances_employee_id'), table_name='salary_advances')
    op.drop_index(op.f('ix_salary_advances_created_by'), table_name='salary_advances')
    op.drop_index(op.f('ix_salary_advances_status'), table_name='salary_advances')
    op.drop_index(op.f('ix_salary_advances_created_at'), table_name='salary_advances')
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_index(op.f('ix_receipts_created_at'), table_name='receipts')
    op.drop_index(op.f('ix_purchases_created_at'), table_name='purchases')
    op.drop_index(op.f('ix_purchase_lines_product_id'), table_name='purchase_lines')
    op.drop_index(op.f('ix_profit_centers_parent_id'), table_name='profit_centers')
    op.drop_index(op.f('ix_profit_centers_manager_id'), table_name='profit_centers')
    op.drop_index(op.f('ix_profit_centers_created_at'), table_name='profit_centers')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_product_warehouse_costs_updated_by_movement_id'), table_name='product_warehouse_costs')
    op.drop_index(op.f('ix_product_warehouse_costs_created_at'), table_name='product_warehouse_costs')
    op.drop_index(op.f('ix_product_serials_sale_line_id'), table_name='product_serials')
    op.drop_index(op.f('ix_product_serials_purchase_line_id'), table_name='product_serials')
    op.drop_index(op.f('ix_product_serials_created_at'), table_name='product_serials')
    op.drop_index(op.f('ix_product_returns_created_at'), table_name='product_returns')
    op.drop_index(op.f('ix_product_return_lines_sale_line_id'), table_name='product_return_lines')
    op.drop_index(op.f('ix_product_return_lines_product_id'), table_name='product_return_lines')
    op.drop_index(op.f('ix_product_partners_created_at'), table_name='product_partners')
    op.drop_index(op.f('ix_product_cost_history_created_at'), table_name='product_cost_history')
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_is_active'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_created_at'), table_name='product_categories')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_payroll_transactions_gl_entry_id'), table_name='payroll_transactions')
    op.drop_index(op.f('ix_payroll_transactions_employee_id'), table_name='payroll_transactions')
    op.drop_index(op.f('ix_payroll_transactions_created_by'), table_name='payroll_transactions')
    op.drop_index(op.f('ix_payroll_transactions_branch_id'), table_name='payroll_transactions')
    op.drop_index(op.f('ix_payroll_transactions_status'), table_name='payroll_transactions')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payment_vault_created_at'), table_name='payment_vault')
    op.drop_index(op.f('ix_payment_transactions_vault_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_logs_vault_id'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_created_at'), table_name='payment_logs')
    op.drop_index(op.f('ix_partners_is_active'), table_name='partners')
    op.drop_index(op.f('ix_partners_created_at'), table_name='partners')
    op.drop_index(op.f('ix_partner_transactions_created_by'), table_name='partner_transactions')
    op.drop_index(op.f('ix_partner_transactions_created_at'), table_name='partner_transactions')
    op.drop_index(op.f('ix_partner_profit_distributions_created_by'), table_name='partner_profit_distributions')
    op.drop_index(op.f('ix_partner_profit_distributions_approved_by'), table_name='partner_profit_distributions')
    op.drop_index(op.f('ix_partner_profit_distributions_status'), table_name='partner_profit_distributions')
    op.drop_index(op.f('ix_partner_profit_distributions_created_at'), table_name='partner_profit_distributions')
    op.drop_index(op.f('ix_partner_commission_entries_sale_line_id'), table_name='partner_commission_entries')
    op.drop_index(op.f('ix_partner_commission_entries_product_id'), table_name='partner_commission_entries')
    op.drop_index(op.f('ix_partner_commission_entries_created_at'), table_name='partner_commission_entries')
    op.drop_index(op.f('ix_packages_is_active'), table_name='packages')
    op.drop_index(op.f('ix_packages_created_at'), table_name='packages')
    op.drop_index(op.f('ix_package_purchases_package_id'), table_name='package_purchases')
    op.drop_index(op.f('ix_package_purchases_created_at'), table_name='package_purchases')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_journal_entry_audits_performed_by'), table_name='journal_entry_audits')
    op.drop_index(op.f('ix_journal_entry_audits_journal_entry_id'), table_name='journal_entry_audits')
    op.drop_index(op.f('ix_invoice_settings_updated_by'), table_name='invoice_settings')
    op.drop_index(op.f('ix_invoice_settings_is_active'), table_name='invoice_settings')
    op.drop_index(op.f('ix_invoice_settings_created_at'), table_name='invoice_settings')
    op.drop_index(op.f('ix_integration_settings_updated_by'), table_name='integration_settings')
    op.drop_index(op.f('ix_integration_settings_created_at'), table_name='integration_settings')
    op.drop_index(op.f('ix_gl_periods_closed_by'), table_name='gl_periods')
    op.drop_index(op.f('ix_gl_periods_created_at'), table_name='gl_periods')
    op.drop_index(op.f('ix_gl_journal_entries_reversed_entry_id'), table_name='gl_journal_entries')
    op.drop_index(op.f('ix_gl_journal_entries_created_by'), table_name='gl_journal_entries')
    op.drop_index(op.f('ix_gl_journal_entries_created_at'), table_name='gl_journal_entries')
    op.drop_index(op.f('ix_gl_accounts_parent_id'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_is_active'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_created_at'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_account_mappings_created_at'), table_name='gl_account_mappings')
    op.drop_index(op.f('ix_fixed_assets_expense_account_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_depreciation_account_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_created_by'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_cost_center_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_asset_account_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_created_at'), table_name='fixed_assets')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_expense_categories_is_active'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_created_at'), table_name='expense_categories')
    op.drop_index(op.f('ix_exchange_rates_created_by'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_created_at'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rate_records_created_by'), table_name='exchange_rate_records')
    op.drop_index(op.f('ix_exchange_rate_records_created_at'), table_name='exchange_rate_records')
    op.drop_index(op.f('ix_error_audit_logs_resolved_by'), table_name='error_audit_logs')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_at'), table_name='employees')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_depreciation_schedules_journal_entry_id'), table_name='depreciation_schedules')
    op.drop_index(op.f('ix_depreciation_schedules_created_at'), table_name='depreciation_schedules')
    op.drop_index(op.f('ix_customs_taxes_gl_account_id'), table_name='customs_taxes')
    op.drop_index(op.f('ix_customs_taxes_is_active'), table_name='customs_taxes')
    op.drop_index(op.f('ix_customs_taxes_created_at'), table_name='customs_taxes')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_currencies_is_active'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_created_at'), table_name='currencies')
    op.drop_index(op.f('ix_cost_centers_parent_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_manager_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_created_at'), table_name='cost_centers')
    op.drop_index(op.f('ix_cheques_created_at'), table_name='cheques')
    op.drop_index(op.f('ix_cash_boxes_created_at'), table_name='cash_boxes')
    op.drop_index(op.f('ix_card_vault_created_by'), table_name='card_vault')
    op.drop_index(op.f('ix_card_vault_is_active'), table_name='card_vault')
    op.drop_index(op.f('ix_card_payments_status'), table_name='card_payments')
    op.drop_index(op.f('ix_budgets_created_by'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_approved_by'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_created_at'), table_name='budgets')
    op.drop_index(op.f('ix_budget_lines_budget_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_account_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_branches_is_active'), table_name='branches')
    op.drop_index(op.f('ix_branches_created_at'), table_name='branches')
    op.drop_index(op.f('ix_bank_reconciliations_created_by'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_bank_account_id'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_approved_by'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_created_at'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliation_items_reconciliation_id'), table_name='bank_reconciliation_items')
    op.drop_index(op.f('ix_bank_reconciliation_items_journal_entry_id'), table_name='bank_reconciliation_items')
    op.drop_index(op.f('ix_bank_reconciliation_items_cheque_id'), table_name='bank_reconciliation_items')
    op.drop_index(op.f('ix_azad_platform_fees_created_at'), table_name='azad_platform_fees')
    op.drop_index(op.f('ix_archived_records_archived_by'), table_name='archived_records')
    op.drop_index(op.f('ix_api_keys_created_by'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_index(op.f('ix_ai_memories_created_at'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_interactions_created_at'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_expertise_created_at'), table_name='ai_expertise')
    op.drop_index(op.f('ix_advanced_expenses_supplier_id'), table_name='advanced_expenses')
    op.drop_index(op.f('ix_advanced_expenses_reversed_by'), table_name='advanced_expenses')
    op.drop_index(op.f('ix_advanced_expenses_gl_journal_entry_id'), table_name='advanced_expenses')
    op.drop_index(op.f('ix_advanced_expenses_created_by'), table_name='advanced_expenses')
    op.drop_index(op.f('ix_advanced_expenses_category_id'), table_name='advanced_expenses')
    op.drop_index(op.f('ix_advanced_expenses_approved_by'), table_name='advanced_expenses')
    op.drop_index(op.f('ix_advanced_expenses_created_at'), table_name='advanced_expenses')
