"""Add azad_platform_fee_rate, subscription fees to SystemSettings, and azad_subscription_fees table.

Revision ID: azad_subs_001
Revises: 2edc56a19e55
Create Date: 2026-06-11 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'azad_subs_001'
down_revision = '2edc56a19e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('azad_platform_fee_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('system_settings', sa.Column('subscription_monthly_fee_aed', sa.Numeric(precision=15, scale=3), nullable=True))
    op.add_column('system_settings', sa.Column('subscription_yearly_fee_aed', sa.Numeric(precision=15, scale=3), nullable=True))
    op.add_column('system_settings', sa.Column('subscription_perpetual_fee_aed', sa.Numeric(precision=15, scale=3), nullable=True))

    op.create_table('azad_subscription_fees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('fee_type', sa.String(length=20), nullable=False),
        sa.Column('amount_aed', sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column('billing_period_start', sa.Date(), nullable=True),
        sa.Column('billing_period_end', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('gl_posted', sa.Boolean(), nullable=False),
        sa.Column('gl_posted_at', sa.DateTime(), nullable=True),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.Column('paid_amount_aed', sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column('payment_method', sa.String(length=50), nullable=True),
        sa.Column('payment_reference', sa.String(length=120), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_azad_subscription_fees_tenant_status', 'azad_subscription_fees', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_azad_subscription_fees_period', 'azad_subscription_fees', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_index(op.f('ix_azad_subscription_fees_tenant_id'), 'azad_subscription_fees', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_azad_subscription_fees_tenant_id'), table_name='azad_subscription_fees')
    op.drop_index('ix_azad_subscription_fees_period', table_name='azad_subscription_fees')
    op.drop_index('ix_azad_subscription_fees_tenant_status', table_name='azad_subscription_fees')
    op.drop_table('azad_subscription_fees')

    op.drop_column('system_settings', 'subscription_perpetual_fee_aed')
    op.drop_column('system_settings', 'subscription_yearly_fee_aed')
    op.drop_column('system_settings', 'subscription_monthly_fee_aed')
    op.drop_column('system_settings', 'azad_platform_fee_rate')
    # ### end Alembic commands ###
