"""Add sales_rep_id, warranty dates, serial imei fields, amount columns

Revision ID: b21dada708de
Revises: 32166124a950
Create Date: 2026-06-10 13:55:34.974910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21dada708de'
down_revision = '32166124a950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_commission_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('product_serials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imei1', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('imei2', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('model_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('iccid', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_product_serials_serial_number'))
        batch_op.create_index(batch_op.f('ix_product_serials_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serials_imei1'), ['imei1'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serials_imei2'), ['imei2'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_serials_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=15, scale=3), nullable=False))

    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('warranty_end_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_rep_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=15, scale=3), nullable=False))
        batch_op.create_index(batch_op.f('ix_sales_sales_rep_id'), ['sales_rep_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['sales_rep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_sales_rep_id'))
        batch_op.drop_column('amount')
        batch_op.drop_column('sales_rep_id')

    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.drop_column('warranty_end_date')
        batch_op.drop_column('warranty_start_date')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('product_serials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_product_serials_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_product_serials_imei2'))
        batch_op.drop_index(batch_op.f('ix_product_serials_imei1'))
        batch_op.drop_index(batch_op.f('ix_product_serials_serial_number'))
        batch_op.create_index(batch_op.f('ix_product_serials_serial_number'), ['serial_number'], unique=True)
        batch_op.drop_column('iccid')
        batch_op.drop_column('model_number')
        batch_op.drop_column('imei2')
        batch_op.drop_column('imei1')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('partner_commission_entries', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
