"""Add industry_code and module_code to gl_accounts

Revision ID: bc1fe09f5956
Revises: d1a3e664dff2
Create Date: 2026-06-10 13:16:36.410995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1fe09f5956'
down_revision = 'd1a3e664dff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('module_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_gl_accounts_industry_code'), ['industry_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_accounts_module_code'), ['module_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_accounts_module_code'))
        batch_op.drop_index(batch_op.f('ix_gl_accounts_industry_code'))
        batch_op.drop_column('module_code')
        batch_op.drop_column('industry_code')

    # ### end Alembic commands ###
