"""sync_model_changes

Revision ID: c98e9930ce80
Revises: payroll_fix_001
Create Date: 2026-06-11 09:58:24.740793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98e9930ce80'
down_revision = 'payroll_fix_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_purchase_id'), ['purchase_id'], unique=False)
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'])

    with op.batch_alter_table('product_serials', schema=None) as batch_op:
        batch_op.create_index('ix_serial_tenant_imei1', ['tenant_id', 'imei1'], unique=False, sqlite_where=sa.text("imei1 IS NOT NULL AND imei1 != ''"), postgresql_where=sa.text("imei1 IS NOT NULL AND imei1 != ''"))
        batch_op.create_index('ix_serial_tenant_imei2', ['tenant_id', 'imei2'], unique=False, sqlite_where=sa.text("imei2 IS NOT NULL AND imei2 != ''"), postgresql_where=sa.text("imei2 IS NOT NULL AND imei2 != ''"))
        batch_op.create_unique_constraint('uq_serial_tenant_serial', ['tenant_id', 'serial_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_serials', schema=None) as batch_op:
        batch_op.drop_constraint('uq_serial_tenant_serial', type_='unique')
        batch_op.drop_index('ix_serial_tenant_imei2', sqlite_where=sa.text("imei2 IS NOT NULL AND imei2 != ''"), postgresql_where=sa.text("imei2 IS NOT NULL AND imei2 != ''"))
        batch_op.drop_index('ix_serial_tenant_imei1', sqlite_where=sa.text("imei1 IS NOT NULL AND imei1 != ''"), postgresql_where=sa.text("imei1 IS NOT NULL AND imei1 != ''"))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_purchase_id'))
        batch_op.drop_column('purchase_id')

    # ### end Alembic commands ###
