"""i18n_refinements_and_schema_sync

Revision ID: cbcda1ac36c4
Revises: 2bae9f7bae92
Create Date: 2026-06-14 22:38:42.753852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcda1ac36c4'
down_revision = '2bae9f7bae92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imported_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('matched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('matched_by', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_matched'))
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_matched_by'), ['matched_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['matched_by'], ['id'])
        batch_op.drop_column('matched')

    op.execute('ALTER TABLE card_payments ALTER COLUMN encrypted_data TYPE BYTEA USING encrypted_data::bytea')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('allowances', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('termination_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('termination_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('annual_leave_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('print_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_history_tenant_doc'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_history_tenant_doc'), ['tenant_id', 'document_type', 'document_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('annual_leave_days')
        batch_op.drop_column('termination_reason')
        batch_op.drop_column('termination_date')
        batch_op.drop_column('allowances')
        batch_op.drop_column('contract_type')

    op.execute('ALTER TABLE card_payments ALTER COLUMN encrypted_data TYPE TEXT')

    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_status'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_matched_by'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_created_by'))
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_matched'), ['matched'], unique=False)
        batch_op.drop_column('matched_by')
        batch_op.drop_column('matched_at')
        batch_op.drop_column('status')
        batch_op.drop_column('created_by')
        batch_op.drop_column('imported_at')
        batch_op.drop_column('source_filename')

    # ### end Alembic commands ###
