"""phase1_stock_architecture_pws_price_tiers_extra_fields

Revision ID: d1a3e664dff2
Revises: f0d25cae300c
Create Date: 2026-06-10 12:49:17.842762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a3e664dff2'
down_revision = 'f0d25cae300c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('extra_fields', sa.JSON(), nullable=True))

    with op.batch_alter_table('shop_loyalty_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_loyalty_transactions_sale_id'), ['sale_id'], unique=False)

    with op.batch_alter_table('shop_newsletters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_newsletters_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('shop_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shop_reviews_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('shop_wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shop_wishlist_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_column('extra_fields')

    with op.batch_alter_table('shop_wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shop_wishlist_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('shop_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shop_reviews_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('shop_newsletters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_newsletters_is_active'))

    with op.batch_alter_table('shop_loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_loyalty_transactions_sale_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('extra_fields')
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
