"""Add DocumentSequence, FiscalPosition, BankStatementLine, Customer.country and fiscal_position_id

Revision ID: e074faa9530c
Revises: a41dbc9113d5
Create Date: 2026-06-11 21:26:19.567146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e074faa9530c'
down_revision = 'a41dbc9113d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('fiscal_position_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_fiscal_position_id'), ['fiscal_position_id'], unique=False)
        batch_op.create_foreign_key(None, 'fiscal_positions', ['fiscal_position_id'], ['id'])

    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.alter_column('is_reconcile',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.alter_column('is_reconcile',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_fiscal_position_id'))
        batch_op.drop_column('fiscal_position_id')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
