"""add subscription_plan_duration

Revision ID: e75de4aeafea
Revises: squash_001
Create Date: 2026-07-14 09:41:19.080798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75de4aeafea'
down_revision = 'squash_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_number', sa.String(length=50), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('starting_cash', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('system_sales_expected', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('actual_cash_counted', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('discrepancy', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_cash_sales', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_card_sales', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pos_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'shift_number', name='uq_pos_shifts_tenant_shift_number')
    )
    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.create_index('idx_pos_shift_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index('idx_pos_shift_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_shifts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_shifts_shift_number'), ['shift_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_shifts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_shifts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_shifts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('package_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_package_purchases_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_duration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('enable_auto_backup', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('enable_auto_backup')
        batch_op.drop_column('subscription_plan_duration')

    with op.batch_alter_table('package_purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_package_purchases_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('pos_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_shifts_user_id'))
        batch_op.drop_index(batch_op.f('ix_pos_shifts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pos_shifts_status'))
        batch_op.drop_index(batch_op.f('ix_pos_shifts_shift_number'))
        batch_op.drop_index(batch_op.f('ix_pos_shifts_session_id'))
        batch_op.drop_index('idx_pos_shift_user_status')
        batch_op.drop_index('idx_pos_shift_session_status')

    op.drop_table('pos_shifts')
    # ### end Alembic commands ###
