"""add_tenant_id_to_audit_logs

Revision ID: ecad0902bdb5
Revises: security_7_5_002
Create Date: 2026-06-06 08:35:49.493874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecad0902bdb5'
down_revision = 'security_7_5_002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('azad_platform_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_azad_platform_fees_idempotency_key'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('azad_platform_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_azad_platform_fees_idempotency_key'), ['idempotency_key'], unique=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
