"""Add warehouse_id, cost_basis, profit_margin, base_currency to partner_commission_entries

Revision ID: edf0e540a237
Revises: 5974516b8de0
Create Date: 2026-06-22 10:53:57.203582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf0e540a237'
down_revision = '5974516b8de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_commission_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('cost_basis', sa.Numeric(precision=15, scale=3), nullable=True))
        batch_op.add_column(sa.Column('profit_margin', sa.Numeric(precision=15, scale=3), nullable=True))
        batch_op.create_index(batch_op.f('ix_partner_commission_entries_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('taxable_amount',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('taxable_amount',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('taxable_amount',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('taxable_amount',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('partner_commission_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_partner_commission_entries_warehouse_id'))
        batch_op.drop_column('profit_margin')
        batch_op.drop_column('cost_basis')
        batch_op.drop_column('base_currency')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
