"""add_shop_models_wishlist_reviews_variants_loyalty_newsletter_abandoned_cart_saved_payment_stock_alert

Revision ID: f0d25cae300c
Revises: audit_001
Create Date: 2026-06-10 12:24:26.479356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d25cae300c'
down_revision = 'audit_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_expertise', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ai_expertise_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ai_interactions_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ai_memories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ai_memories_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gl_account_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_account_mappings_is_active'), ['is_active'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_gl_account_mappings_tenant_id_tenants'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('product_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_partners_partner_customer_id'), ['partner_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_partners_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    with op.batch_alter_table('product_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_partners_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_partners_partner_customer_id'))

    with op.batch_alter_table('gl_account_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_gl_account_mappings_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_gl_account_mappings_is_active'))

    with op.batch_alter_table('ai_memories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_memories_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_interactions_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ai_expertise', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_expertise_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
