"""
Regenerates migrations/versions/squash_001_baseline.py.

This is the source-of-truth generator for the squashed baseline. It needs an
autogenerated explicit schema first, so run it in TWO steps:

  Step 1 (autogenerate explicit schema into a throwaway migration):
    # move the active baseline + legacy/ out of migrations/versions/ so the
    # script dir is empty, then:
    ./.venv/Scripts/python.exe -m flask db migrate -m t --rev-id test1
    # (run with DATABASE_URL pointing at a FRESH empty database)
    # copy migrations/versions/test1_t.py aside, then restore baseline + legacy/

  Step 2 (build the real baseline from test1_t.py):
    ./.venv/Scripts/python.exe build_baseline.py
    # then DELETE migrations/versions/test1_t.py (it is only a temp input)

The generator emits:
  * Explicit, fully-compiled schema (op.create_table per table). Tables are
    created WITHOUT inline FKs; all foreign keys are added in a second pass
    after every table exists (handles cyclic dependencies).
  * Schema only -- NO tenant data is seeded. Tenants (e.g. demo) are provisioned
    by the dedicated seed commands at runtime.
"""

import os, sys, glob, re, shutil

sys.path.insert(0, os.path.dirname(__file__))

from sqlalchemy import create_engine, text

MAIN_DB_URL = "postgresql+psycopg2://postgres:123@localhost:5432/azad_uae"
VERSIONS_DIR = os.path.join(os.path.dirname(__file__), "migrations", "versions")
GEN_SRC = os.path.join(VERSIONS_DIR, "test1_t.py")  # autogenerated explicit schema
OUT = os.path.join(VERSIONS_DIR, "squash_001_baseline.py")

# ---------------------------------------------------------------------------
# 1. Pure-data imports (no DB, no models)
# ---------------------------------------------------------------------------
from models.gl_account_registry import (
    BASE_ACCOUNTS,
    INDUSTRY_EXTENSIONS,
    GL_MODULE_DEFINITIONS,
)
from models._constants import GL_CONCEPT_REGISTRY, RESOLUTION_MODE_MAPPING

# ---------------------------------------------------------------------------
# 2. Canonical baseline config (used only to compute the schema; no tenant is
#    seeded -- tenants are provisioned at runtime via the seed commands).
# ---------------------------------------------------------------------------
business_type = "general"
default_currency = "ILS"


def flag_on(name):
    return False


# ---------------------------------------------------------------------------
# 3. Compute gl_accounts to create
# ---------------------------------------------------------------------------
accounts = {}


def add_acc(tmpl, industry_code=None, module_code=None):
    if tmpl.code in accounts:
        return
    accounts[tmpl.code] = (
        tmpl.code,
        tmpl.name,
        tmpl.name_ar,
        tmpl.type,
        tmpl.level,
        tmpl.is_header,
        tmpl.parent_code,
        industry_code or tmpl.industry_code,
        module_code or tmpl.module_code,
    )


for tmpl in sorted(BASE_ACCOUNTS, key=lambda a: a.level):
    add_acc(tmpl)

if business_type in INDUSTRY_EXTENSIONS:
    for tmpl in INDUSTRY_EXTENSIONS[business_type]:
        add_acc(tmpl, industry_code=business_type)

for mod in GL_MODULE_DEFINITIONS.values():
    if mod.required or (mod.feature_flag and flag_on(mod.feature_flag)):
        for tmpl in mod.accounts:
            add_acc(tmpl, module_code=mod.module_code)

ACCOUNTS = [accounts[c] for c in sorted(accounts, key=lambda code: (len(code), code))]

# ---------------------------------------------------------------------------
# 4. Compute gl_account_mappings to create (mapping-owned concepts only)
# ---------------------------------------------------------------------------
MAPPINGS = []
seen = set()
for mod in GL_MODULE_DEFINITIONS.values():
    if mod.required or (mod.feature_flag and flag_on(mod.feature_flag)):
        for m in mod.mappings:
            meta = GL_CONCEPT_REGISTRY.get(m.concept_code)
            if not meta or meta.get("resolution_mode") != RESOLUTION_MODE_MAPPING:
                continue
            key = (m.concept_code, m.account_code)
            if key in seen:
                continue
            seen.add(key)
            MAPPINGS.append((m.concept_code, m.account_code))

print(f"[info] business_type={business_type} currency={default_currency}")
print(
    f"[info] schema-only baseline; accounts/mappings computed but NOT seeded (provisioned at runtime)"
)

# ---------------------------------------------------------------------------
# 5. Extract explicit schema body from autogenerated file, then split into:
#    (a) CREATE TABLE statements WITHOUT inline FK constraints,
#    (b) batch_alter_table blocks (indexes / batch FKs),
#    (c) FK constraints emitted in a SECOND pass after every table exists.
#    This avoids any FK ordering / cyclic-dependency problems entirely.
# ---------------------------------------------------------------------------
src_lines = open(GEN_SRC, encoding="utf-8").read().splitlines()
start = None
for i, ln in enumerate(src_lines):
    if "commands auto generated by Alembic" in ln:
        start = i + 1
        break
schema_body = "\n".join(src_lines[start:]).rstrip("\n")
# test1_t.py contains its own (empty) downgrade(); strip it out so we only
# keep the upgrade() body.
cut = schema_body.find("\n\ndef downgrade():")
if cut != -1:
    schema_body = schema_body[:cut].rstrip("\n")


def _split_schema(body):
    lines = body.split("\n")
    n = len(lines)
    creates, batches = [], []
    i = 0
    while i < n:
        line = lines[i]
        if "op.create_table(" in line:
            m = re.search(r"op\.create_table\('([^']+)'", line)
            tbl = m.group(1) if m else None
            depth = 0
            started = False
            buf = []
            j = i
            while j < n:
                ln = lines[j]
                buf.append(ln)
                for ch in ln:
                    if ch == "(":
                        depth += 1
                        started = True
                    elif ch == ")":
                        depth -= 1
                if started and depth == 0:
                    break
                j += 1
            creates.append((tbl, "\n".join(buf)))
            i = j + 1
        elif "with op.batch_alter_table(" in line:
            m = re.search(r"with op\.batch_alter_table\('([^']+)'", line)
            tbl = m.group(1) if m else None
            base_indent = len(line) - len(line.lstrip())
            buf = [line]
            j = i + 1
            while j < n:
                ln = lines[j]
                if ln.strip() == "":
                    buf.append(ln)
                    j += 1
                    continue
                if (len(ln) - len(ln.lstrip())) <= base_indent:
                    break
                buf.append(ln)
                j += 1
            batches.append((tbl, "\n".join(buf)))
            i = j
        else:
            i += 1
    return creates, batches


def _strip_inline_fks(unit_text):
    """Remove sa.ForeignKeyConstraint(...) occurrences (balanced parens)."""
    out = []
    i = 0
    n = len(unit_text)
    while i < n:
        if unit_text.startswith("sa.ForeignKeyConstraint(", i):
            depth = 0
            j = i
            while j < n:
                if unit_text[j] == "(":
                    depth += 1
                elif unit_text[j] == ")":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            # skip the trailing comma + whitespace/newline
            j += 1
            while j < n and unit_text[j] in ", \t\r\n":
                j += 1
            i = j
        else:
            out.append(unit_text[i])
            i += 1
    return "".join(out)


def _extract_fks(unit_text, table):
    """Return list of (constraint_name, local_cols, ref_table, ref_cols, ondelete)."""
    fks = []
    i = 0
    n = len(unit_text)
    while i < n:
        if unit_text.startswith("sa.ForeignKeyConstraint(", i):
            depth = 0
            j = i
            while j < n:
                if unit_text[j] == "(":
                    depth += 1
                elif unit_text[j] == ")":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            chunk = unit_text[i : j + 1]
            m = re.match(
                r"sa\.ForeignKeyConstraint\(\s*(?:'([^']+)'\s*,\s*)?"
                r"\[([^\]]*)\],\s*\[([^\]]*)\](.*)\)\s*$",
                chunk,
                re.S,
            )
            if m:
                name = m.group(1)
                local = [
                    c.strip().strip("'") for c in m.group(2).split(",") if c.strip()
                ]
                refs = [
                    c.strip().strip("'") for c in m.group(3).split(",") if c.strip()
                ]
                rest = m.group(4) or ""
                ondel = re.search(r"ondelete='([^']*)'", rest)
                ondel = ondel.group(1) if ondel else None
                ref_table = refs[0].split(".")[0]
                ref_cols = [r.split(".", 1)[1] for r in refs]
                if not name:
                    name = "fk_" + table + "_" + "_".join(local)
                fks.append((name, local, ref_table, ref_cols, ondel))
            i = j + 1
        else:
            i += 1
    return fks


creates, batches = _split_schema(schema_body)

phase_a = []  # CREATE TABLE without inline FKs
phase_c_fks = []  # (table, name, local, ref_table, ref_cols, ondelete)
table_names = []
for tbl, txt in creates:
    table_names.append(tbl)
    clean = _strip_inline_fks(txt)
    phase_a.append(clean)
    for fk in _extract_fks(txt, tbl):
        phase_c_fks.append((tbl,) + fk)

# Phase B: original batch_alter_table blocks (indexes / batch FKs).
phase_b = [btxt for _, btxt in batches]

# Build FK-add pass as batch_alter_table blocks.
fk_lines = []
for tbl, name, local, ref_table, ref_cols, ondel in phase_c_fks:
    local_repr = "[" + ", ".join("'%s'" % c for c in local) + "]"
    ref_repr = "[" + ", ".join("'%s'" % c for c in ref_cols) + "]"
    ondel_arg = ", ondelete='%s'" % ondel if ondel else ""
    fk_lines.append(
        "    with op.batch_alter_table('%s'):\n"
        "        op.create_foreign_key(%s, '%s', '%s', %s, %s%s)"
        % (tbl, "'" + name + "'", tbl, ref_table, local_repr, ref_repr, ondel_arg)
    )

schema_body = "\n".join(phase_a)
if phase_b:
    schema_body += "\n\n" + "\n".join(phase_b)
if fk_lines:
    schema_body += "\n\n" + "\n".join(fk_lines)


# ---------------------------------------------------------------------------
# 6. Build the data-seeding block (idempotent SQL, no app services)
# ---------------------------------------------------------------------------
def py_literal_accounts():
    items = []
    for code, name, name_ar, typ, level, is_header, parent_code, ind, mod in ACCOUNTS:
        items.append(
            "    (%r, %r, %r, %r, %d, %r, %r, %r, %r),"
            % (code, name, name_ar, typ, level, bool(is_header), parent_code, ind, mod)
        )
    return "\n".join(items)


def py_literal_mappings():
    items = ["    (%r, %r)," % (c, a) for (c, a) in MAPPINGS]
    return "\n".join(items)


data_block = (
    ""  # schema-only baseline; tenants provisioned at runtime via seed commands
)

downgrade_lines = []
for t in reversed(table_names):
    downgrade_lines.append(f'    op.execute(text("DROP TABLE IF EXISTS {t} CASCADE"))')
downgrade_body = "\n".join(downgrade_lines)

# ---------------------------------------------------------------------------
# 7. Assemble final migration file
# ---------------------------------------------------------------------------
header = '''"""Squashed explicit platform baseline.

Revision ID: squash_001
Revises:
Create Date: 2026-07-12

This is a fully-squashed baseline. The schema is compiled explicitly with
op.create_table() (NO db.create_all() / NO live-model dependency). It creates
the full platform schema (tables, indexes, foreign keys) and provides an
explicit downgrade. NO tenant data is seeded here -- tenants (e.g. demo) are
provisioned by the dedicated seed commands at runtime.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


revision = 'squash_001'
down_revision = None
branch_labels = None
depends_on = None

'''

tail = (
    "\n\ndef upgrade():"
    + schema_body
    + data_block
    + """

def downgrade():
"""
    + downgrade_body
    + "\n"
)

content = header + tail

with open(OUT, "w", encoding="utf-8") as f:
    f.write(content)

print(
    f"[ok] wrote {OUT}  ({len(content)} bytes, {len(table_names)} tables, downgrade drops in reverse)"
)
