import psycopg2

conn = psycopg2.connect('postgresql://postgres:123@localhost:5432/azad_test')
cur = conn.cursor()
cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('roles','users','tenants','products','customers') ORDER BY table_name")
print('Tables:', [r[0] for r in cur.fetchall()])
cur.execute('SELECT id, slug FROM roles LIMIT 5')
print('Roles:', cur.fetchall())
cur.execute('SELECT id, username FROM users LIMIT 5')
print('Users:', cur.fetchall())
cur.execute('SELECT id, name FROM tenants LIMIT 5')
print('Tenants:', cur.fetchall())
cur.execute('SELECT id, name FROM products LIMIT 5')
print('Products:', cur.fetchall())
cur.execute('SELECT id, name FROM customers LIMIT 5')
print('Customers:', cur.fetchall())
cur.close()
conn.close()