#!/usr/bin/env python3
"""Seed Babel .po catalogs from the existing TRANSLATIONS dict in utils/i18n.py.

Usage:
    python scripts/seed_translations.py

Reads utils/i18n.py, extracts the TRANSLATIONS dict, and writes
translations/ar/LC_MESSAGES/messages.po and translations/en/LC_MESSAGES/messages.po.

Run after adding new translatable strings, or when the TRANSLATIONS dict changes.
"""

import ast
import os
from datetime import UTC, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
I18N_PATH = os.path.join(ROOT, "utils", "i18n.py")
AR_PO = os.path.join(ROOT, "translations", "ar", "LC_MESSAGES", "messages.po")
EN_PO = os.path.join(ROOT, "translations", "en", "LC_MESSAGES", "messages.po")


def extract_translations_dict():
    with open(I18N_PATH, encoding="utf-8") as f:
        source = f.read()

    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "TRANSLATIONS":
                    return ast.literal_eval(node.value)
    raise SystemExit("TRANSLATIONS dict not found in utils/i18n.py")


def escape_po(text):
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", '\\n"\n"')


def write_po(filepath, lang, translations):
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M+0000")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"# Translation catalog for {lang}\n")
        f.write("# Generated by scripts/seed_translations.py — do not edit manually\n")
        f.write("#\n")
        f.write('msgid ""\n')
        f.write('msgstr ""\n')
        f.write('"Project-Id-Version: Azad-UAE 2.0\\n"\n')
        f.write('"Report-Msgid-Bugs-To: \\n"\n')
        f.write(f'"POT-Creation-Date: {now}\\n"\n')
        f.write('"Last-Translator: \\n"\n')
        f.write(f'"Language-Team: {lang}\\n"\n')
        f.write(f'"Language: {lang}\\n"\n')
        f.write('"MIME-Version: 1.0\\n"\n')
        f.write('"Content-Type: text/plain; charset=utf-8\\n"\n')
        f.write('"Content-Transfer-Encoding: 8bit\\n"\n')
        f.write(
            '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n'
            if lang == "en"
            else '"Plural-Forms: nplurals=6; plural=(n==0 || n==1 || n==2 || n%100>=3 && n%100<=10 || n%100>=11);\\n"\n'
        )
        f.write("\n")

        for msgid, langs in sorted(translations.items()):
            msgstr = langs.get(lang, "")
            f.write(f'msgid "{escape_po(msgid)}"\n')
            f.write(f'msgstr "{escape_po(msgstr)}"\n')
            f.write("\n")

    count = len(translations)
    print(f"  {filepath}: {count} entries written")


def main():
    print("Extracting TRANSLATIONS from utils/i18n.py...")
    translations = extract_translations_dict()
    print(f"  Found {len(translations)} translatable strings")

    print("Writing Arabic catalog...")
    write_po(AR_PO, "ar", translations)

    print("Writing English catalog...")
    write_po(EN_PO, "en", translations)

    print("Done. Next steps:")
    print("  1. Run: pybabel compile -d translations")
    print("  2. To update after dict changes: python scripts/seed_translations.py && pybabel compile -d translations")


if __name__ == "__main__":
    main()
