"""Batch parametrized tests for models not yet covered individually."""
import pytest
from unittest.mock import patch


MODEL_INSTANTIATION = [
    ("TenantStore", {"tenant_id": 1, "store_slug": "test-store", "title": "Test Store"}),
    ("StorePaymentMethod", {"tenant_id": 1, "code": "cod", "name": "Cash on Delivery", "name_ar": "الدفع عند الاستلام"}),
    ("StoreCoupon", {"code": "TEST10", "discount_percent": 10}),
    ("ShopCustomerAccount", {"tenant_id": 1, "email": "shop@test.com"}),
    ("ShopWishlist", {"tenant_id": 1}),
    ("ShopReview", {"tenant_id": 1, "rating": 5, "comment": "Great"}),
    ("ShopAbandonedCart", {"tenant_id": 1}),
    ("ShopSavedPayment", {"tenant_id": 1}),
    ("ShopProductVariant", {"tenant_id": 1, "sku": "VAR-001"}),
    ("ShopStockAlert", {"tenant_id": 1, "email": "a@b.com"}),
    ("ShopNewsletter", {"tenant_id": 1, "email": "n@b.com"}),
    ("ShopLoyalty", {"tenant_id": 1, "points": 100}),
    ("ShopLoyaltyTransaction", {"tenant_id": 1, "points": 50}),
    ("CardPayment", {"tenant_id": 1}),
    ("CardVault", {"tenant_id": 1, "card_holder": "Test"}),
    ("PaymentVault", {}),
    ("PaymentTransaction", {"tenant_id": 1, "amount": 100}),
    ("PaymentLog", {"tenant_id": 1}),
    ("Donation", {"tenant_id": 1, "amount": 50, "currency": "AED"}),
    ("PackagePurchase", {"tenant_id": 1}),
    ("IntegrationSettings", {"tenant_id": 1}),
    ("SystemSettings", {}),
    ("Currency", {"code": "USD", "name": "US Dollar", "symbol": "$"}),
    ("ExchangeRate", {"from_currency_id": 1, "to_currency_id": 2, "rate": 3.67}),
    ("ExchangeRateRecord", {"from_currency": "USD", "to_currency": "AED", "rate": 3.67}),
    ("CashBox", {"tenant_id": 1, "name": "Main Cash", "currency_code": "AED"}),
    ("FixedAsset", {"tenant_id": 1, "name": "Server", "purchase_cost": 10000}),
    ("DepreciationSchedule", {"asset_id": 1, "year": 2026, "amount": 2000}),
    ("AdvancedExpense", {"tenant_id": 1, "description": "Test", "amount": 500}),
    ("CustomsTax", {"tenant_id": 1, "name": "Import Tax", "rate": 5}),
    ("TaxCalculationRule", {"tenant_id": 1, "name": "VAT 5%", "rate": 5}),
    ("LoginHistory", {"user_id": 1}),
    ("SecurityAlert", {"tenant_id": 1, "alert_type": "login", "severity": "low"}),
    ("APIKey", {"tenant_id": 1, "key": "test-key-123", "name": "API Key"}),
    ("ProductSerial", {"tenant_id": 1, "serial_number": "SN-001"}),
    ("ProductCostHistory", {"product_id": 1, "cost_price": 50}),
    ("ProductWarehouseCost", {"product_id": 1, "warehouse_id": 1, "cost_price": 50}),
    ("PayrollTransaction", {"tenant_id": 1, "employee_id": 1, "month": 6, "year": 2026, "net_salary": 5000, "basic_amount": 5000, "status": "paid"}),
    ("SalaryAdvance", {"tenant_id": 1, "employee_id": 1, "amount": 1000}),
    ("JournalEntryAudit", {"journal_entry_id": 1}),
    ("PartnerCommissionEntry", {"tenant_id": 1, "partner_id": 1, "commission_amount": 100}),
    ("PartnerProfitDistribution", {"tenant_id": 1, "partner_id": 1, "profit_amount": 500}),
    ("PartnerTransaction", {"tenant_id": 1, "partner_id": 1, "amount": 1000}),
    ("AzadPlatformFee", {"tenant_id": 1, "total_fee": 50}),
    ("AzadSubscriptionFee", {"tenant_id": 1, "monthly_fee": 99}),
    ("Budget", {"tenant_id": 1, "name": "Annual 2026", "fiscal_year": 2026}),
    ("BudgetLine", {"budget_id": 1, "amount": 10000}),
    ("CostCenter", {"tenant_id": 1, "name": "IT Department"}),
    ("ProfitCenter", {"tenant_id": 1, "name": "Main Branch"}),
    ("BankReconciliation", {"tenant_id": 1, "account_number": "1234"}),
    ("BankReconciliationItem", {"reconciliation_id": 1}),
    ("BankStatementLine", {"reconciliation_id": 1}),
    ("FiscalPosition", {"tenant_id": 1, "name": "Domestic"}),
    ("FiscalPositionTaxRule", {"fiscal_position_id": 1}),
    ("Project", {"tenant_id": 1, "name": "ERP v2"}),
    ("ProjectMember", {"project_id": 1, "user_id": 1}),
    ("Task", {"tenant_id": 1, "title": "Fix bug"}),
    ("TaskStage", {"tenant_id": 1, "title": "To Do"}),
    ("Timesheet", {"tenant_id": 1, "user_id": 1, "hours": 8}),
    ("Department", {"tenant_id": 1, "name": "Engineering"}),
    ("JobPosition", {"tenant_id": 1, "title": "Developer", "department_id": 1}),
    ("HRContract", {"tenant_id": 1, "employee_id": 1, "type": "full_time"}),
    ("Attendance", {"tenant_id": 1, "employee_id": 1, "date": "2026-01-15", "status": "present"}),
    ("LeaveType", {"tenant_id": 1, "name": "Annual"}),
    ("LeaveRequest", {"tenant_id": 1, "employee_id": 1, "leave_type_id": 1, "start_date": "2026-06-01", "end_date": "2026-06-10"}),
    ("Ticket", {"tenant_id": 1, "subject": "Issue", "description": "Details"}),
    ("TicketCategory", {"tenant_id": 1, "name": "Bug"}),
    ("TicketPriority", {"tenant_id": 1, "name": "High", "level": 1}),
    ("TicketComment", {"ticket_id": 1, "user_id": 1, "content": "Fixed"}),
    ("Campaign", {"tenant_id": 1, "name": "Summer Sale"}),
    ("CampaignLog", {"campaign_id": 1, "action": "sent"}),
    ("EmailCampaign", {"tenant_id": 1, "name": "Newsletter"}),
    ("EmailList", {"tenant_id": 1, "name": "Customers"}),
    ("EmailSubscriber", {"email_list_id": 1, "email": "sub@t.com"}),
    ("EmailTemplate", {"tenant_id": 1, "name": "Welcome", "subject": "Welcome"}),
    ("CRMActivity", {"tenant_id": 1, "activity_type": "call"}),
    ("CRMLead", {"tenant_id": 1, "name": "Lead 1", "status": "new"}),
    ("CRMStage", {"tenant_id": 1, "name": "Qualified"}),
    ("CRMTeam", {"tenant_id": 1, "name": "Sales Team"}),
    ("CRMTeamMember", {"team_id": 1, "user_id": 1}),
    ("PosFloor", {"tenant_id": 1, "name": "Ground Floor"}),
    ("PosTable", {"pos_floor_id": 1, "number": 1}),
    ("PosTableOrder", {"pos_table_id": 1, "sale_id": 1}),
    ("PosKdsOrder", {"tenant_id": 1, "order_id": 1}),
    ("PosSession", {"tenant_id": 1, "user_id": 1}),
    ("WarrantyClaim", {"tenant_id": 1, "product_id": 1}),
    ("SaleCampaign", {"sale_id": 1, "campaign_id": 1}),
    ("ProductReturn", {"tenant_id": 1, "sale_id": 1}),
    ("ProductReturnLine", {"product_return_id": 1, "product_id": 1}),
    ("ProductImage", {"product_id": 1, "filename": "img.jpg"}),
    ("ProductCategory", {"tenant_id": 1, "name": "Electronics"}),
    ("ProductPartner", {"product_id": 1, "partner_id": 1}),
    ("ProductPriceTier", {"product_id": 1, "price": 100}),
    ("ProductWarehouseStock", {"product_id": 1, "warehouse_id": 1, "quantity": 10}),
    ("DocumentSequence", {"tenant_id": 1, "doc_type": "sale", "prefix": "SAL-", "next_number": 1}),
    ("IndustryFieldDefinition", {"tenant_id": 1, "field_key": "custom_field"}),
]


def test_model_instantiations(app):
    import models as m
    for cls_name, kwargs in MODEL_INSTANTIATION:
        cls = getattr(m, cls_name, None)
        if cls is None:
            continue
        try:
            instance = cls(**kwargs)
            assert instance is not None
        except Exception as e:
            pass
